Odim 5623: Support for Update BMC account
lpooja/ODIM pull request #16
Opened 2022-03-25 11:44 UTC by lpooja

2022-03-25 11:50 UTC, jeevan-kamkar approved these changes

2022-03-25 12:18 UTC, shivacharanms approved these changes

2022-03-25 12:25 UTC, irappa-pattar requested changes

2022-03-25 12:25 UTC, irappa-pattar commented on svc-api/handle/managers.go
> +		errorMessage := "while trying to create JSON request body in create remote account: " + err.Error()
update remote account

2022-03-25 12:25 UTC, irappa-pattar commented on svc-managers/managers/managers.go
> +		log.Error("while marshalling the create BMC account request: " + err.Error())
update account

2022-03-25 12:25 UTC, irappa-pattar commented on svc-managers/mgrmodel/manager.go
> +	Password string `json:"Password"`
add omitempty

2022-03-25 12:32 UTC, lpooja commented on svc-api/handle/managers.go
> +		errorMessage := "while trying to create JSON request body in create remote account: " + err.Error()
addressed

2022-03-25 12:32 UTC, lpooja commented on svc-managers/managers/managers.go
> +		log.Error("while marshalling the create BMC account request: " + err.Error())
addressed

2022-03-25 12:38 UTC, irappa-pattar approved these changes

2022-03-28 05:41 UTC, amar-shalgar approved these changes
LGTM

2022-03-28 05:41 UTC, merged