Odim 5930: Unit test coverage for agcommon under svc-aggregation
lpooja/ODIM pull request #22
Opened 2022-06-01 07:30 UTC by lpooja

Updated Test case for svc-aggregation

2022-06-01 08:49 UTC, jeevan-kamkar requested changes
address the requested changes

2022-06-01 08:49 UTC, jeevan-kamkar commented on svc-aggregation/agcommon/common_test.go
> +
remove the newly added lines

2022-06-01 08:49 UTC, jeevan-kamkar commented on svc-aggregation/agcommon/common_test.go
> +		// ip=append(ip, net.ParseIP("192.100.10.4"))
remove the commented code

2022-06-01 09:31 UTC, lpooja commented on svc-aggregation/agcommon/common_test.go
> +
removed

2022-06-01 09:31 UTC, lpooja commented on svc-aggregation/agcommon/common_test.go
> +		// ip=append(ip, net.ParseIP("192.100.10.4"))
removed

2022-06-01 11:57 UTC, chauberahul1993 commented on svc-aggregation/agcommon/common_test.go
> +		// TODO: Add test cases.
No test case Added, Remove if not required

2022-06-01 11:58 UTC, hemkapoor approved these changes

2022-06-01 12:03 UTC, lpooja commented on svc-aggregation/agcommon/common_test.go
> +		// TODO: Add test cases.
removed

2022-06-01 12:05 UTC, chauberahul1993 approved these changes

2022-06-01 14:52 UTC, jeevan-kamkar approved these changes

2022-06-02 04:47 UTC, amar-shalgar approved these changes

2022-06-02 10:12 UTC, merged